version: '3'
services:
  tprn_manifest:
    build: .
    environment:
      - "DATA_OUT_DIR=${DATA_OUT_DIR:-outputs}"
      - "AWS_DEFAULT_REGION=${AWS_REGION:-us-east-1}"
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
      - "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}"
      - "AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}"
      # - "DRY_UPLOAD=True"
    volumes:
      - "${TPRN_OUT_DATA_DIR:-./outputs}:/tprn_manifest/outputs"
      # - .:/tprn_manifest # used for development work, mount the current code into the container

volumes:
  outputs:
