version: '3'
services:
  tprn_data:
    build: .
    environment:
      - "DATA_IN_DIR=${DATA_IN_DIR:-inputs}"
      - "DATA_OUT_DIR=${DATA_OUT_DIR:-outputs}"
      # - "AWS_DEFAULT_REGION=${AWS_REGION:-us-east-1}"
      # - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      # - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
      # - "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}"
      # - "AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}"
    volumes:
      - "${TPRN_IN_DATA_DIR:-./inputs}:/tprn_data/inputs"
      - "${TPRN_OUT_DATA_DIR:-./outputs}:/tprn_data/outputs"
      - .:/tprn_data # remove this after dev, it's used to inject the latest code
      # - ${HOME}/.panoptes/:/root/.panoptes/ # IS THIS A USEFUL WAY TO GO?
